<a href="<?= $this->basePath()?>/user">Retour page User</a></br>
<body> 
	
	<h1>Séries populaire :  </h1>
    <div id="result">
		<?php for($i=0; $i<sizeof($resultat);$i++): ?>
		    <a href="<?= $this->basePath()?>/serie/<?= $resultat[$i]->show->ids->slug?>">
				<img src="<?= $imageOMDB[$i]->Poster?>" alt="Poster">
		    	<?= $resultat[$i]->show->title?> (<?=$resultat[$i]->show->year ?>)
		    </a><hr>
		    
		<?php endfor ?>
    </div>

    <hr>

    <div>
		<?php if($numPage > 1): ?>
			<a href="<?= $this->basePath()?>/listeseries/<?= $numPage-1;?>">Page précedente </a>   
		<?php endif;?>
		<?php if($numPage < $nbPages): ?>
			<a href="<?= $this->basePath()?>/listeseries/<?= $numPage+1;?>">Page suivante </a>    
		<?php endif;?>
	</div>  

</body>

