<main>
    <span><strong>Nom d'utilisateur : </strong><?=$this->escapeHtml($username)?></span><br>
    <span><strong>Adresse mail : </strong><?=$this->escapeHtml($mail)?></span><br>

    <form action="<?=$this->basePath()?>/user/administration/changerMail" method="post">
        <span><strong>Changer email</strong></span><input type="email" name="mail"/>
        <button type="submit">Envoyer</button>
    </form>

    <form action="<?=$this->basePath()?>/user/administration/changerPhoto" method="post">
        <span><strong>Changer photo</strong></span><input type="url" name="url"/>
        <button type="submit">Envoyer</button>
    </form>

</main>