<h2>Page User</h2>

<hr>

<a href="<?= $this->basePath()?>/listeseries/1?recherche=">Découvrir des séries</a></br>

<a href="<?= $this->basePath()?>/user/administration">Administration du compte</a></br>
<a href="<?= $this->basePath()?>/user/stats">Stats utilisateurs</a></br><hr>
<span><strong>Avatar : </strong></span><br>
<img class="avatar" src="<?= $this->user->_picture?>"/><br>

<span><strong>Id utilisateur : </strong> <?= $this->user->_id?></span><br>
<span><strong>Nom d'utilisateur : </strong> <?= $this->user->_username?></span><br>
<span><strong>Mail d'utilisateur : </strong> <?= $this->user->_mail?></span><br>

<hr>
<h3>Séries en cours</h3>

<?php foreach ($seriesEnCours as $serie): ?>
    <a href="<?= $this->basePath()?>/serie/<?= $serie->_idSerie?>"><?= $serie->_idSerie?></a><br>
<?php endforeach;?>

<hr>


<h3>Séries à démarrer</h3>

<?php foreach ($seriesADemarrer as $serie): ?>
    <a href="<?= $this->basePath()?>/serie/<?= $serie->_idSerie?>"><?= $serie->_idSerie?></a><br>
<?php endforeach;?>

<hr>

<h3>Séries favorites</h3>
<?php foreach ($seriesFavorites as $serie): ?>
    <a href="<?= $this->basePath()?>/serie/<?= $serie->_idSerie?>"><?= $serie->_idSerie?></a><br>
<?php endforeach;?>

