Index (/user/)</br>
<a href="<?= $this->basePath()?>/user/administration">/user/administration</a></br>
<a href="<?= $this->basePath()?>/user/stats">/user/stats</a></br> <br>

<a href="<?= $this->basePath()?>/serie/1">/serie/1</a></br>
<a href="<?= $this->basePath()?>/serie/1/saison/1">/serie/1/saison/1</a></br>
<a href="<?= $this->basePath()?>/serie/1/saison/2">/serie/1/saison/2</a></br></br>


<a href="<?= $this->basePath()?>/serie/2">/serie/2</a></br>
<a href="<?= $this->basePath()?>/serie/2/saison/1">/serie/2/saison/1</a></br>
<a href="<?= $this->basePath()?>/serie/2/saison/2">/serie/2/saison/2</a></br></br>

