Série <?=$idSerie?>

<body >
	<br><a href="<?= $this->basePath()?>/user">Retour page user</a>
	<br>
	<img src="<?= $image->Poster?>" alt="Poster">
    <h1><?=$serie->title?></h1>  
    Date de sortie : <?=$serie->year?> <br>

	<a href="<?= $this->basePath()?>/serie/<?=$idSerie;?>/ajout">Ajouter à ma liste</a><br>
    <a href="<?= $this->basePath()?>/serie/<?=$idSerie;?>/favoris">Ajouter à mes favoris</a><br>
    <a href="<?= $this->basePath()?>/serie/<?=$idSerie;?>/supprfavoris">Supprimer de mes favoris</a><br>
    <hr>
    <h1>Saisons: </h1>
	<?php 
	$lengthObject = count($saison); 
	for($i=0; $i<$lengthObject; $i++): ?>
	    <a href="<?= $this->basePath()?>/serie/<?= $this->idSerie?>/saison/<?= $i?>"><?= $saison[$i]->number?></a><br>
	<?php endfor ?>
	<hr>

</body>