Série <?=$idSerie?>

<body onload="getShow('titre','<?=$idSerie?>','title');
            getShow('année','<?=$idSerie?>','year');
            getSeasons('saisons','<?=$idSerie?>');
            getPosterSeasonIMDB('poster','<?=$idSerie?>');
            getEpisodeTitle('titres_episodes','<?=$idSerie?>','1');
            ">
    <script src="../js/script.js" type="text/javascript"></script>

    <h1>Titre:  </h1>
    <div id="titre"></div>

    <h1>Date de sortie: </h1>
    <div id="année"></div>

    <h1>Saisons: </h1>
    <div id="saisons"></div>

    <h1>Image</h1>
    <div id="poster"></div>

     <h1>Nom des episodes saison 1</h1>
    <div id="titres_episodes"></div>
</body>